export const cancelList = [
  "ser gado demais",
  "ser atraente demais",
  "procrastinar demais",
  "ser uma delícia",
  "ser poser",
  "ser insuportável",
  "ser atraente demais",
  "ser inadimplente no Serasa",
  "ser trouxa",
  "ser corno",
  "se considerar incancelável",
  "ser insensível",
  "não fazer nada",
  "ser BV",
  "ser inteligente demais",
  "ser comunista",
  "ter virado o Coronga",
  "ter muita preguiça",
  "ser corno",
  "debochar demais",
  "pedir muito biscoito",
  "ter charme demais",
  "ser uma grande gostosa",
  "se atrasar sempre",
  "ser boy lixo",
  "contar muita piada ruim",
  "ser impaciente demais",
  "ser ancap",
  "ser gay",
  "ser hétero",
  "ser prata",
  "ser monochampion",
  "ser tóxico",
  "ser irritante",
  "mamar demais",
  "banir Ezreal",
  "jogar ARAM",
  "jogar URF",
  "ser da PanelaCraft",
  "ser mono Yuumi",
  "ser fã de Jojo",
  "usar iPhone",
  "ouvir kpop",
  "ser talarico",
  "ser emo",
  "ser bolsonarista",
  "apertar o haxixe",
  "ser terraplanista",
  "ser otaku",
  "ser matta sub",
  "ver hentai",
  "jogar freefire",
  "fazer rerun",
  "mandar caule",
  "comprar pack do pé",
  "vender pack do pé",
  "faltar na catequese",
  "bater na mãe com toalha molhada",
  "jogar de Lulu",
  "entrar no rule34",
  "participar do nofap",
  "gostar de furry",
  "ser nerdola",
  "colocar foto de anime no perfil",
  "pickar Janna",
  "colocar feijão por cima do arroz",
  "tomar banho sem chinelo",
  "ser um arrombado",
  "assistir Maicon Küster",
  "participar do banho dos campeões",
  "não tomar banho",
  "pedir mod e vip",
  "não tomar vacina",
  "ser hater da yamafia",
  "ser torcedor da CNB",
  "tomar cloroquina",
  "fazer sexo com as mãos",
  "assistir naruto",
  "skipar a música",
  "ser incel",
];
